INSERT INTO STUDENT  (id, name, address, email, phone_number, student_type) values (student_seq.nextval,'Tim Flucker','123 Main Street','tflucker@email.com','555-555-5555','UNDERGRAD');
INSERT INTO STUDENT  (id, name, address, email, phone_number, student_type) values (student_seq.nextval,'John Smith','456 River Avenue','jsmith@email.com','555-555-5555','UNDERGRAD');
INSERT INTO STUDENT  (id, name, address, email, phone_number, student_type) values (student_seq.nextval,'Catherine Lawson','9831 Apple Street','clawson@email.com','555-555-5555','UNDERGRAD');
INSERT INTO STUDENT  (id, name, address, email, phone_number, student_type) values (student_seq.nextval,'Natalie Griffin','91 Law Street','ngriffin@email.com','555-555-5555','UNDERGRAD');
INSERT INTO STUDENT  (id, name, address, email, phone_number, student_type) values (student_seq.nextval,'Chris Kane','70 Rey Road','ckane@email.com','555-555-5555','UNDERGRAD');

INSERT INTO COURSE (id, course_name, min_size, max_size, course_description, teacher_name, course_type) values(course_seq.nextval, 'Biology 101', 5, 30, 'Introduction to study of biology.', 'Mr. Smith', 'CLASSROOM');
INSERT INTO COURSE (id, course_name, min_size, max_size, course_description, teacher_name, course_type) values (course_seq.nextval, 'Chemistry 101', 5, 30 , 'Introduction to study of chemistry.', 'Mrs. Winters', 'CLASSROOM');
INSERT INTO COURSE (id, course_name, min_size, max_size, course_description, teacher_name, course_type) values (course_seq.nextval, 'Drawing Fundamentals', 10, 20, 'Solidfy foundations in sketching and drawing.', 'Mr. Evans', 'CLASSROOM');
INSERT INTO COURSE (id, course_name, min_size, max_size, course_description, teacher_name, course_type) values (course_seq.nextval, 'Race in Media',10,40,'Discussions about how race is portrayed in a variety of media.','Ms. Tasha','SEMINAR');
INSERT INTO COURSE (id, course_name, min_size, max_size, course_description, teacher_name, course_type) values (course_seq.nextval, 'Circuit Theory 1',5,30,'Learn basics about circuits','Mr. Farnsworth','CLASSROOM');
INSERT INTO COURSE (id, course_name, min_size, max_size, course_description, teacher_name, course_type) values (course_seq.nextval, 'Sociology 101',10,20,'Dicuss early and modern theories and philosophies surrounding human interaction.','Ms. Jay','CLASSROOM');
INSERT INTO COURSE (id, course_name, min_size, max_size, course_description, teacher_name, course_type) values (course_seq.nextval, 'Single Variable Calculus 1',10,30,'Part 1 in Single Variable Calculus','Mr. Rabinovich','CLASSROOM');
INSERT INTO COURSE (id, course_name, min_size, max_size, course_description, teacher_name, course_type) values (course_seq.nextval, 'Spanish 101',10,30,'Beginner conversational spanish','Mr. Garcia','CLASSROOM');
INSERT INTO COURSE (id, course_name, min_size, max_size, course_description, teacher_name, course_type) values (course_seq.nextval, 'French 101',10,30,'Beginner conversational french','Ms. Bernard','CLASSROOM');
INSERT INTO COURSE (id, course_name, min_size, max_size, course_description, teacher_name, course_type) values (course_seq.nextval, 'Java Programming Fundamentals',10,20,'Core concepts of the java language and its implementation','Mr. Dawson','CLASSROM');
